### ISSUE TITLE
design locale representation

### ISSUE THREAD

**Issue by mrhota** [ogham/rust-locale#11] opened 2016-04-05 06:30 UTC
See [locale objects](https://github.com/rust-locale/rust-locale/wiki/Locale-objects) wiki page.

**Comment by mrhota** [comment] 2016-04-05 06:32
I reorganized the wiki page. I've taken a liking to the kind of language used in the ECMA-402 spec, so I used a bit of it to describe a couple of abstract locale constructors. Enjoy!

**Comment by mrhota** [comment] 2016-04-05 06:35
I don't know if we need two different types of locales---one with strict adherence to BCP47 and one without---but it helps illustrate the possible use-case for "lenient" and "strict" constructors of some kind.

**Comment by jan-hudec** [comment] 2016-04-05 08:08
Requirement: Locales _must_ be able to represent any setting possible on Linux, Windows, OSX and Android

RFC5646 alone is not sufficient to achieve that, so here is the grammar:

```
locale = tag *( ":" [ category "=" ] tag )
tag = langtag
    / irregular
category = 1*ALPHANUM
langtag = language
        [ SEP script ]
        [ SEP region ]
        *( SEP variant )
        *( SEP extension )
language = 2*3ALPHA [ SEP 3ALPHA ]
script = 4ALPHA
region = 2ALPHA
       / 3DIGIT
variant = 5*8ALPHANUM
        / DIGIT 3ALPHANUM
extension = ALPHANUM 1*( SEP 2*8ALPHANUM )
irregular = ALPHANUM SEP *( SEP / ALPHANUM )
```

The `langtag` mostly follows RFC5646, except:
- Our private use has the same format as other extensions, so it does not get a separate production.
- The `4*8ALPHA` variant of `language` is omitted and only one sublanguage is accepted for now, because nothing of the other forms is defined.
  - Depending on whether we end up calling the root "root" in CLDR-style or "und" in RFC5646-style we might need to enable the 4*ALPHA production.
- The irregular is a bit leaner to cover the `i-something` irregulars and `x-so-me-thi-n-g` privates.

The Unix complex settings are supported using the alternate tags. E.g. if the environment has

```
LANGUAGE=cs:en_GB:en
LANG=cs_CZ
LC_MESSAGES=en_GB
```

the corresponding language tag will be

```
cs-CZ:messages=en-GB:cs:en-GB:en
```

(this is relatively simple variable settings; user can go _wild_ with the `LANGUAGE`, `LANG` and `LC_*` variables)

On the other hand on Windows complex settings may involve overriding specific options, so somebody might set `English (USA)`, but 24-hour format and we'll get

```
en-US-u-hc-h23
```

(`h23` means hours go 00–23, `h24` means they go 24, 01–23; I don't think Windows distinguishes the two and I don't think it ever uses the later)

Where there is no `u` extension keyword, we define our own in the same format, so on Windows if somebody sets `English (USA)`, but group separator as `␠`, we'll get

```
en-US-x-gs-0080
```

(0080 is codepoint for non-breaking space)

Additionally Windows have a UI locale. I have no clue when it should be used, but we can represent it as `ui` subcategory. So we may get e.g.

```
en-US-u-hc-h23-ms-metric-x-gs-0080:ui=cs-CZ-x-ds-002e
```

And it also has a system language, which will probably end up as alternate at the end.

Besides functions for splitting the tag to the components (including actually interpreting the `u` and `x` extensions we are going to use) we will need function to get the next alternate tag and tag for specific category, which each facet will ask for. Which will return the non-specific tag if there is no specific one, so

```
Locale"cs-CZ:messages=en-GB:cs:en-GB:en".category("messages")
```

will return

```
Locale"en-GB:cs:en-GB:en"
```

while

```
Locale"cs-CZ:messages=en-GB:cs:en-GB:en".category("time")
```

will return

```
Locale"cs-CZ:cs:en-GB:en"
```

I am not yet sure whether the specific facet query should return the following non-specific alternates, i.e. whether

```
Locale"cs-CZ:messages=en-GB:cs:en-GB:en".category("messages")
```

is `Locale"en-GB:cs:en-GB:en"` or `Locale"en-GB" or whether the`LANGUAGE` alternates should be placed before or after the category overrides, i.e whether the above configuration should return

```
Locale"cs-CZ:messages=en-GB:cs:en-GB:en"
```

or

   Locale"cs-CZ:cs:en-GB:en:messages=en-GB"

(in the later case, the alternates would not be returned for `messages` even if the function did return the following alternates in that case; it will definitely not return anything before the category tag).

Yes, it is a bit complicated. But the systems can actually be configured that way and Rust programs should follow

**Comment by jan-hudec** [comment] 2016-04-05 09:56
I have rewritten the https://github.com/rust-locale/rust-locale/wiki/Locale-objects again, with the above design.

**Comment by mrhota** [comment] 2016-04-05 14:12
libc and GNU back to haunt us again... Isn't that where these language tag monstrosities come from?

Can we just stick to BCP47 for now? Is there a good reason why we have to support, from the beginning, _exactly_ what libc supports? We've already decided to postpone `/usr/share/locale`-DB support...

**Comment by jan-hudec** [comment] 2016-04-05 14:36
No, we can't. Not on Windows and not on Unix. I am not relaxing the requirement of representing the system settings in their entirety.

**Comment by jan-hudec** [comment] 2016-04-05 14:58
By the way, this is not about GNU. Windows is actually bigger offender here, because it allows overriding _each and every item_ separately. And users are used to it and expect software to honour their settings.

Also, don't take Java as a good example. It is a horrible example more often than not.

**Comment by mrhota** [comment] 2016-04-05 15:52
> don't take Java as a good example. It is a horrible example more often than not.

haha I thought the same of C++! I'd like to know your reasoning, perhaps in a new wiki page for criticisms of extant libraries and APIs?

When we take a hard stance for a feature, it would be nice if we provide an explanation and/or justification. We need to be able to reference it later, and everyone else on this project should be able to understand our reasoning.

---

OK, so there are two issues here and only one that actually concerns me.
1. rust-locale should be able to represent (for some definition of "represent") system settings completely.
2. rust-locale should provide this support wholly in language tags.

It's 2 I'm not sure about. Departing completely from BCP47 language tags in order to represent complete system settings in _one string_ is not necessary.

#### A better way

We can represent system settings in different ways: a map, a "system settings" struct, etc. "Representation" of system settings is open-ended, luckily.

Let's say we define an abstract operation called `BuildSettingsFromEnvironment` that returns a suitable data structure containing one `Locale` per env setting<sup>1</sup>. This would let our language tag parser maintain BCP47 compliance.

---

<sup>1</sup> It looked like each individual component in your original comment was (or could be) BCP47 compliant. Hence, one `Locale` from `LANG`, one from `LC_CTYPES`, one from `LANGUAGES`, etc. If the C++-like locale-as-container is used, obviously the return value of `BuildSettingsFromEnvironment` would be one `Locale` with its facets filled in with the correct "stuff".

**Comment by mrhota** [comment] 2016-04-05 15:59
The guiding principle I have in mind when I suggest the above is: `Locale`'s constructor should remain as simple as possible and comply with BCP47.

If it should depart from the standard, we should have a Very Good Reason.

Lacking any compelling argument against it, I think we can parse env. settings in a separate place without concatenating all the things into one string and parsing it.

**Comment by jan-hudec** [comment] 2016-04-05 18:20
> haha I thought the same of C++! I'd like to know your reasoning, perhaps in a new wiki page for criticisms of extant libraries and APIs?

C++ is (generally) designed quite well for orthogonality and extensibility. And while the `locale` module is not the best example of it, it is still pretty good at it. It is an interface that a library can implement and the application can set it and everything then uses it. And libraries do extend it and new revisions of the standard extend it.

And for casual use, it is still simple. You just set the default instance, or if you need to switch them, take appropriate instance and imbue it in the `basic_stream`. The verbose facet stuff is for extending it.

In contrast, Java libraries either are not all that extensible, or are insanely convoluted to work around limitations of the language. Locales seem to be a case of the former: I don't see a way to e.g. install a new `NumberFormat`.

> When we take a hard stance for a feature, it would be nice if we provide an explanation and/or justification.

The features are mostly there in the use-case list. Ok, I should probably add a general principle: “Application must respect all settings that the user generally expects applications on their system to obey.”

> It's 2 I'm not sure about. Departing completely from BCP47 language tags in order to represent complete system settings in one string is not necessary.

Actually, it seems to be a _purely terminological problem_. For me, `Locale` is what represents the user preferences (as matches the C/C++ use of the term), while for you `Locale` is the single language and user may request different for each category (as matches the Java use of the term). We just need less ambiguous names for them.

Also, we both clearly have both concepts. In what I described, the single language is there, as the fundamental basic building block, just under name _tag_. It absolutely is not departing completely from BCP47; it is building on it.

Ok, so let's call the RFC5646 tag a `LanguageTag` in accordance with that RFC and lets call the complete set of user preferences `RegionalSettings` (I would gladly accept better proposal for the later).

Now Java does not seem to have any single-object representation of the `RegionalSettings`, but I think it is very useful to have it so that applications that need to switch between them don't need to switch category by category.

Now whether the `LanguageTag` and `RegionalSettings` are stored internally as strings or some kind of collections of components does not really matter. However both should have string representations and `RegionalSettings` should consist of primary `LanguageTag`, zero or more fallback `LanguageTag`s and optional category-specific override for open-ended list of categories. And above I described that on the string representation.

The reason to have primary tag and optional overrides is to allow the category list to be open-ended. Windows only have two categories, “messages” (which they call UI) and the rest. POSIX and C++ standards have six categories: “collate”, “ctype”, “messages”, “monetary”, “numeric” and “time”. GNU LibC adds fiver more “address”, “measurement”, “name”, “paper” and “telephone” (the “identification” is not really a category). And some application or library might just come up with something more (though the most obvious case of units is covered by “measurement”). So we need to know which language tag applies to category that was not specifically configured.

> The guiding principle I have in mind when I suggest the above is: Locale's constructor should remain as simple as possible and comply with BCP47.

BCP47 is a tool, not a virtue on its own. The ultimate goal is to represent the user settings.

And since the confusion was caused by different idea what should be called `Locale`, lets not call anything by that name from now on (except the library itself; it is not confusing there).

**Comment by jan-hudec** [comment] 2016-04-05 18:39
> It looked like each individual component in your original comment was (or could be) BCP47 compliant.

It was very explicitly BCP47-compliant. And it was exactly what you wanted and I refused to call “locale”, because for me the goal was from the start to represent the system settings and this intermediate step was not particularly interesting.

> I think we can parse env. settings in a separate place without concatenating all the things into one string and parsing it.

We are designing _interface, not implementation_.

The parsing of system settings will only happen somewhere deep in the library and all the user will see is the `user()`, `global()` and `current()` instances of `RegionalSettings`. Hm, that name is really long, given it will be the type users will most often need to manipulate, but if we are to avoid `Locale` to avoid confusing people coming from Java, I am currently out of ideas. `Culture` does not work for me, because culture is more like the `LanguageTag`. This should try to capture the fact that it is the representation of the personal quirks of the particular user.

**Comment by mrhota** [comment] 2016-04-05 19:25
> I don't see a way to e.g. install a new `NumberFormat`.

https://docs.oracle.com/javase/8/docs/api/java/util/spi/LocaleServiceProvider.html

---

I don't see any reason to avoid the name `Locale` now that you've clarified and distinguished the usage of `LanguageTag`. I'm happy with that!

**Comment by jan-hudec** [comment] 2016-04-05 20:03
> https://docs.oracle.com/javase/8/docs/api/java/util/spi/LocaleServiceProvider.html

I'll take a look. Java is not a language I regularly use and the documentation is not so easy for me to navigate in.

> I don't see any reason to avoid the name `Locale`

It will probably be a bit confusing for other people with Java background too, but if we don't come up with something else _short_, with proper documentation, it should do.

**Comment by mrhota** [comment] 2016-04-07 06:37
@jan-hudec @ogham I'd like to be made a contributor. I have a languagetag prototype I want to put into a branch here.

**Comment by jan-hudec** [comment] 2016-04-07 07:08
@mrhota, I fixed the permissions so all members have write everywhere (and you are a member).

**Comment by jan-hudec** [comment] 2016-04-07 07:45
Some technical notes I have so far:
- The `LanguageTag`, `Locale`, and appropriate global instances, should live in an auxiliary subcrate, `locale_core`. I am just not sure whether to create a new repository for it or just include it in a subdirectory. The reason is to avoid (we can't prevent it, but we should be able to avoid most reasons for it) having multiple copies of the global instances in a single application by having `locale` always depend on the latest `locale_core`, so even with multiple versions of `locale`, the underlying `locale_core` should hopefully be the same.
- `LanguageTag` is very much tied to string, so maybe we should have a `LanguageTag` for borrowed str. One idea I had is defining `struct LanguageTag<'a> { inner: std::borrow::Cow<'a str>, }` and giving it `Borrow<LanguageTag<'a>>` and method `into_static(&self) -> LanguageTag<'static>`. That would also give more freedom to internal implementation of `Locale`—with owned string in `LanguageTag` we would have to store `Locale` as collection of `LanguageTag`s (or make a lot of copies, which feels unrusty).
- The alternate is to use [interning](https://en.wikipedia.org/wiki/String_interning) not only for `Locale`s, but also for `LanguageTag`s. I haven't looked whether Rust has any tool for this or we need to do it ourselves.
- I am still not sure whether to pull in [nom](https://crates.io/crates/nom) to do the parsing (for RFC5645 and Unix tags, and sometimes whichever we have) or write it by hand (in more-or-less similar style).
- What about eventually making `nom` basis of the parsing side of localization. We want to do parsing dates, numbers etc. too and having the generic parser form use the `nom` signature would make it easy to build on.

**Comment by jan-hudec** [comment] 2016-04-27 18:41
Ok, I decided to keep the regexes, at least for now. It should be mostly written in https://github.com/rust-locale/rust-locale/commit/8c8560c79bf49747a132bfa136f79ecfb36b3568.

What is left is getting the tags from `Locale` and subtags from `LanguageTag`. I am currently thinking that:
- `Locale` should return `Iterator<LanguageTag>` that apply to provided category.
- `LanguageTag` should have methods to get the:
  - language (`&str`)
  - script (`&str`)
  - region (`&str`)
  - iterator over variants (`Iterator<&str>`)
  - iterator over extensions (`Iterator<(char, &str)>`)
  
  The last one is somewhat tricky. The `char` is the extension type, which might be any lowercase letter or number, but in practice it may only be `t`, `u` or `x`. And the value is the individual extension. The reason for the split is that it should split the known extensions by their substructure. For example `en-IN-u-ca-buddhist-cu-eur-tz-deber` has just one `u`, but actually 3 extensions: `('u', "ca-buddhist"), ('u', "cu-eur"), ('u', "tz-deber")`. I was even thinking about splitting it further, but it would only make sense for the `u` and `x` extensions, but not the others like `t` that are not in the form of keyword-value.

**Comment by jan-hudec** [comment] 2016-05-19 18:05
It should be there, the only thing left is wrapping the implementation in `locale_core` with equivalent implementation in `Locale`.

**Comment by jan-hudec** [comment] 2016-06-02 17:44
I think it is essentially designed and implemented, so we can close this now so we don't drown in issues.

**Closed as completed by jan-hudec** 2016-06-02 17:44 UTC
